# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [25]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import time
import json
from pprint import pprint
# Import API key
from config import weather_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data = pd.read_csv("../WeatherPy/weather_output.csv")
weather_data.head()

,City,Country,Lat,Lng,Temp,Cloudiness,Humidity,Wind Speed
0,Ust-Maya,RU,60.4167,134.5333,37.33,100,94,3.29
1,Barrow,US,71.2906,-156.7887,19.40,90,86,9.22
2,Albany,US,42.6001,-73.9662,55.45,80,89,2.86
3,Northport,US,33.2290,-87.5772,74.50,1,64,6.91
4,Ancud,CL,-41.8697,-73.8203,56.12,90,100,10.36

### Humidity Heatmap
* Configure gmaps.
* Drop any rows will null values.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# configure gmaps with API key
gmaps.configure(api_key=weather_key)

In [4]:
# drop null values from DataFrame
weather_data = weather_data.dropna()

In [5]:
# store 'Lat' and 'Lng' into locations
locations = weather_data[["Lat", "Lng"]]
# store humidities
humidity = weather_data["Humidity"].astype(float)

In [6]:
# add heatmap layer to map
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,dissipating=False,max_intensity=100,point_radius=2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Store into variable named `hotel_df`.

In [7]:
hotel_df = pd.DataFrame(weather_data.loc[(weather_data["Temp"] < 80) & (weather_data["Temp"] > 70) & (weather_data["Wind Speed"] < 10) & (weather_data["Cloudiness"] == 0)])
hotel_df

,City,Country,Lat,Lng,Temp,Cloudiness,Humidity,Wind Speed
22,Cabedelo,BR,-6.9811,-34.8339,75.20,0,94,2.30
132,Carnarvon,AU,-24.8667,113.6333,77.00,0,50,6.91
182,Safaga,EG,26.7292,33.9365,71.60,0,18,6.91
267,Chu,KZ,43.5983,73.7614,73.33,0,37,6.40
282,Abaetetuba,BR,-1.7181,-48.8825,77.00,0,94,5.75
342,Bayeux,BR,-7.1250,-34.9322,75.20,0,94,2.30
347,Poum,NC,-20.2333,164.0167,75.69,0,51,4.12
517,Conde,BR,-7.2597,-34.9075,75.20,0,94,2.30
523,Morondava,MG,-20.2833,44.2833,76.03,0,74,5.73
533,Almaty,KZ,43.2500,76.9500,71.60,0,35,4.47

### Hotel Map
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [35]:
# add hotel name column
hotel_df["Hotel Name"] = np.nan
# reset index and drop "index" column that is created
hotel_df = hotel_df.reset_index()
hotel_df = hotel_df.drop(columns="index")

# set parameters to search for hotels within 5000 meters
params = {"key":weather_key,
          "types":"lodging",
          "rankby":"distance"
         }


for index, row in hotel_df.iterrows():
    # store rows lat and lng into variables
    lat = row["Lat"]
    lng = row["Lng"]
    
    # update params dictionary with locations
    params["location"] = f"{lat}, {lng}"
    
    # craete base_url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    hotel_response = requests.get(base_url, params=params).json()
    # use try except block to avoid missing data
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_response["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing result... skipping")
        
hotel_df

,City,Country,Lat,Lng,Temp,Cloudiness,Humidity,Wind Speed,Hotel Name
0,Cabedelo,BR,-6.9811,-34.8339,75.20,0,94,2.30,Suites Praia Formosa
1,Carnarvon,AU,-24.8667,113.6333,77.00,0,50,6.91,Tilly Gia home sweet home
2,Safaga,EG,26.7292,33.9365,71.60,0,18,6.91,Joya resort
3,Chu,KZ,43.5983,73.7614,73.33,0,37,6.40,Shyngyzkhan
4,Abaetetuba,BR,-1.7181,-48.8825,77.00,0,94,5.75,hotel 3 irmaõs
5,Bayeux,BR,-7.1250,-34.9322,75.20,0,94,2.30,Jf ferragens
6,Poum,NC,-20.2333,164.0167,75.69,0,51,4.12,Gîte kajeon
7,Conde,BR,-7.2597,-34.9075,75.20,0,94,2.30,Sulga lombra
8,Morondava,MG,-20.2833,44.2833,76.03,0,74,5.73,Hotel Sharone
9,Almaty,KZ,43.2500,76.9500,71.60,0,35,4.47,Mika City Hotel

In [29]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [34]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))