# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [8]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import weather_key
#from config import

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [10]:
weather_data_df = pd.read_csv("../WeatherPy/weather_output.csv")
weather_data_df

,City,Country,Lat,Lng,Temp,Cloudiness,Humidity,Wind Speed
0,Ust-Maya,RU,60.4167,134.5333,37.33,100,94,3.29
1,Barrow,US,71.2906,-156.7887,19.40,90,86,9.22
2,Albany,US,42.6001,-73.9662,55.45,80,89,2.86
3,Northport,US,33.2290,-87.5772,74.50,1,64,6.91
4,Ancud,CL,-41.8697,-73.8203,56.12,90,100,10.36
...,...,...,...,...,...,...,...,...
557,Praia da Vitória,PT,38.7333,-27.0667,57.70,75,94,8.32
558,Eureka,US,40.8021,-124.1637,51.80,66,87,5.10
559,Taksimo,RU,56.3444,114.8794,32.40,47,51,1.61
560,Virginia Beach,US,36.8529,-75.9780,73.53,40,60,12.66
561,Ossora,RU,59.2353,163.0719,33.28,100,98,4.68

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure